# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
#
parties = Party.create([
                         { name: "Liberal Party of Australia",
                           votes: 0},
                         { name: "Australian Labor Party",
                           votes: 0},
                         { name: "Australian Greens",
                           votes: 0},
                         { name: "Animals Justice Party",
                           votes: 0},
                         { name: "Australian National Party",
                           votes: 0},
                         { name: "One Nation",
                           votes: 0},
                         { name: "Family First ",
                           votes: 0},
                         { name: "Legalise Cannabis Party",
                           votes: 0}
                       ])

candidates = Candidate.create!([
                                 { name: "John Adam",
                                   party: "Liberal Party of Australia",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Susie Smith",
                                   party: "Australian Labor Party",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Xavier Barns",
                                   party: "Australian Greens",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Paul Rudd",
                                   party: "Animals Justice Party",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Tony Stark",
                                   party: "Australian National Party",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Steve Rogers",
                                   party: "One Nation",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Donald Trumpet",
                                   party: "Family First ",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Happy Harold ",
                                   party: "Australian Greens",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Mary-Jane Dope",
                                   party: "Legalise Cannabis Party",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Che Downs",
                                   party: "Liberal Party of Australia",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Agatha Brown",
                                   party: "Animals Justice Party",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                                 { name: "Logan Paul",
                                   party: "One Nation",
                                   votes: 0,
                                   birthday: '8/08/2008'},
                               ])